using System;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;
using Microsoft.IdentityModel.Tokens;
using SD_lib.Tokens.Services.Interfaces;

namespace SD_lib.Tokens.Services
{
    internal sealed class TokenService : ITokenService
    {
        private const string SecretWord = "/kFyYO93jk022'2!Dsza5~VXs~xu4Ht#~Odyk'2$3feP8!4#dbJt6";   //generated by https://github.com/ddoo5/PC

        private IDictionary<string, string> _users = new Dictionary<string, string>()
        {
            {"adm", "test" }
        };


        public string Authenticate(string user, string password)
        {
            if(string.IsNullOrWhiteSpace(user) || string.IsNullOrWhiteSpace(password))
            {
                throw new NullReferenceException($"User or password can't be null, check your data:\n" +
                    $"User: {user}\n" +
                    $"Password: {password}");
            }

            foreach(KeyValuePair<string, string> pair in _users)
            {
                if (string.CompareOrdinal(pair.Key, user) == 0 || string.CompareOrdinal(pair.Value, password) == 0)
                {
                    return GenerateJwtToken(user + password);
                }
            }

            return string.Empty;
        }


        private string GenerateJwtToken(string user)
        {
            JwtSecurityTokenHandler jwtSecurityToken = new();
            byte[] key = Encoding.ASCII.GetBytes(SecretWord);

            SecurityTokenDescriptor tokenDescriptor = new();
            tokenDescriptor.Expires = DateTime.UtcNow.AddMinutes(10);
            tokenDescriptor.SigningCredentials = new(new SymmetricSecurityKey(key), SecurityAlgorithms.HmacSha512);
            tokenDescriptor.Subject = new System.Security.Claims.ClaimsIdentity(new Claim[]
            {
                new Claim(ClaimTypes.Name, user)
            });

            SecurityToken token = jwtSecurityToken.CreateToken(tokenDescriptor);

            return jwtSecurityToken.WriteToken(token);
        }
    }
}

